# Generated by Django 3.2.5 on 2021-09-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('age', models.IntegerField(default='')),
            ],
            options={
                'db_table': 'Book1',
            },
        ),
    ]
